FROM base-builder:{{ codename }}-latest
LABEL maintainer="{{ vendor }} <{{ vendor_email }}>"

# Setup

WORKDIR /home/builder
USER builder

# build

CMD ["sh", "-c", "/bin/mv *.deb ./deb/{{ codename }}"]
