FROM base-builder:{{ codename }}-latest
LABEL maintainer="{{ vendor }} <{{ vendor_email }}>"

ENV DEBIAN_FRONTEND noninteractive

# Setup

RUN adduser --shell /bin/bash --disabled-password --gecos "" builder
WORKDIR /home/builder
USER builder

# build

CMD ["sh", "-c", "/bin/mv *.deb ./deb/{{ codename }}"]
