{% if arch %}
FROM base-builder:{{ codename }}-{{ arch }}-latest
{% else %}
FROM base-builder:{{ codename }}-latest
{% endif %}
LABEL maintainer="{{ vendor }} <{{ vendor_email }}>"

# Setup anything here that needs root, e.g. package installs, new repos, etc.

WORKDIR /home/builder
USER builder

# build instructions

# When building with `shared_package: true`:
# CMD ["sh", "-c", "/bin/mv *.deb ./deb/all"]

# When doing fully targetted builds:
CMD ["sh", "-c", "/bin/mv *.deb ./deb/{{ codename }}"]

