#!/bin/bash

cat >/tmp/changelog <<EOF
libmail-srs-perl ($( head -1 libmail-srs-perl-0.31/debian/changelog | awk '{ print $2 }' | sed -e s/\[\(\)\]//g)+ms1) unstable; urgency=low

  * Add "socketfile" option to /usr/bin/srsd to permit overriding the
    default location for the socket used by the daemon process.

 -- mySociety <sysadmin@mysociety.org>  $(date -R)

EOF

cat libmail-srs-perl-${SRS_VERSION}/debian/changelog >> /tmp/changelog

mv /tmp/changelog libmail-srs-perl-${SRS_VERSION}/debian/changelog
cp src/srsd libmail-srs-perl-${SRS_VERSION}/srsd
cd libmail-srs-perl-${SRS_VERSION}
dpkg-buildpackage -b --no-sign
cd ..
mv *.deb deb/$(lsb_release -cs)/
