FROM {{ distro }}:{{ codename }}
LABEL maintainer="sysadmin@mysociety.org"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq && \
      apt-get install -qq build-essential curl git libffi-dev ruby-dev apt-transport-https lsb-release >/dev/null

RUN curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

RUN echo 'deb https://deb.nodesource.com/node_14.x {{ codename }} main' > /etc/apt/sources.list.d/nodesource.list \
      && echo 'deb-src https://deb.nodesource.com/node_14.x {{ codename }} main' >> /etc/apt/sources.list.d/nodesource.list

RUN apt-get update -qq && apt-get install -qq nodejs >/dev/null

RUN gem install --no-document fpm

RUN adduser --shell /bin/bash --disabled-password --gecos "" builder
WORKDIR /home/builder
USER builder
RUN fpm -s npm -t deb \
      --vendor "mySociety" \
      --maintainer "mySociety <sysadmin@mysociety.org>" \
      --license "MIT" \
{% for dependency in dependencies %}
      --depends "{{ dependency }}" \
{% endfor %}
      --iteration "{{ iteration }}" \
      jshint@{{ version }}

CMD ["sh", "-c", "/bin/mv *.deb ./deb/{{ codename }}"]
