FROM {{ distro }}:{{ codename }}
LABEL maintainer="{{ vendor}} <{{ vendor_email }}>"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq && \
      apt-get install -qq build-essential curl git libffi-dev ruby-dev >/dev/null

RUN gem install --no-document fpm

RUN adduser --shell /bin/bash --disabled-password --gecos "" builder
USER builder

WORKDIR /home/builder
RUN git clone --recursive https://github.com/mysociety/misc-scripts.git
COPY src/postinst .
COPY src/postrm .

WORKDIR /home/builder/misc-scripts
#RUN git checkout {{ version }}
RUN ["/bin/bash", "-c", "rm -fr {.git*,cpan,rotatelogs,run-with-lockfile,package*}"]
RUN fpm -s dir -t deb \
      --vendor "{{ vendor }}" \
      --maintainer "{{ vendor}} <{{ vendor_email }}>" \
      --version "{{ version }}" \
      --iteration "{{ iteration }}" \
      --url "https://github.com/mysociety/misc-scripts" \
      --description "Lock a file and then execute a program." \
      --after-install ../postinst \
      --after-remove ../postrm \
{% for dependency in dependencies %}
      --depends "{{ dependency }}" \
{% endfor %}
{% for suggestion in suggests %}
      --deb-suggests "{{ suggestion }}" \
{% endfor %}
      -n "mysociety-misc-scripts" \
      ./=/data/mysociety/

CMD ["sh", "-c", "/bin/mv *.deb ../deb/{{ codename }}"]
