FROM {{ distro }}:{{ codename }}
LABEL maintainer="{{ vendor}} <{{ vendor_email }}>"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq && \
      apt-get install -qq build-essential curl git libffi-dev ruby-dev >/dev/null

RUN gem install --no-document fpm

RUN adduser --shell /bin/bash --disabled-password --gecos "" builder
USER builder

WORKDIR /home/builder
RUN git clone https://github.com/mysociety/run-with-lockfile.git

WORKDIR /home/builder/run-with-lockfile
RUN make
RUN fpm -s dir -t deb \
      --vendor "{{vendor}}" \
      --maintainer "{{ vendor}} <{{ vendor_email }}>" \
      --version "{{ version }}" \
      --license "{{ license }}" \
      --iteration "{{ iteration }}" \
      --url "https://github.com/mysociety/run-with-lockfile" \
      --description "Lock a file and then execute a program." \
      -n "run-with-lockfile" \
      ./run-with-lockfile=/usr/local/bin/run-with-lockfile

CMD ["sh", "-c", "/bin/mv *.deb ../deb/{{ codename }}"]
