#!/bin/sh

set -e

cd "$(dirname "$0")/.."

VIRTUALENV="venv"
if [ ! -f "${VIRTUALENV}/bin/activate" ] ; then
    echo "==> Setting up virtualenv at ${VIRTUALENV}..."
    python -m venv $VIRTUALENV
    . ${VIRTUALENV}/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
fi

if ! command -v docker >/dev/null ; then
    echo "==> Docker is required, so please ensure this is installed and available."
    exit 1
fi
