FROM {{ distro }}:{{ codename }}
LABEL maintainer="{{ vendor }} <{{ vendor_email }}>"

ENV DEBIAN_FRONTEND noninteractive
ENV DEBEMAIL {{ vendor_email }}
ENV DEBFULLNAME {{ vendor }}
ENV SOURCE_VERSION {{ source_version }}

RUN apt-get update && \
      apt-get install -y \
        build-essential \
        dh-make-perl \
        swig \
        wget

RUN adduser --shell /bin/bash --disabled-password --gecos "" builder
WORKDIR /home/builder
USER builder
{% if codename == "xenial" %}
RUN git config --global user.email "{{ vendor_email }}" \
      && git config --global user.name "{{ vendor }}"
{% endif %}
RUN wget -q https://github.com/mysociety/String-Ediff/archive/v${SOURCE_VERSION}.tar.gz \
      -O libstring-ediff-perl_${SOURCE_VERSION}.orig.tar.gz && \
      tar xf libstring-ediff-perl_${SOURCE_VERSION}.orig.tar.gz

WORKDIR /home/builder/String-Ediff-${SOURCE_VERSION}
RUN dh-make-perl && dpkg-buildpackage

WORKDIR /home/builder
CMD ["sh", "-c", "/bin/mv libstring-ediff-perl*_${SOURCE_VERSION}-1* ./deb/{{ codename }}"]
