FROM {{ distro }}:{{ codename }}
ENV DEBIAN_FRONTEND noninteractive
COPY sources.list.{{ codename }} /etc/apt/sources.list

RUN apt-get update -qq \
      && apt-get install -qq \
          apt-transport-https \
          build-essential \
          curl \
          devscripts \
          fakeroot \
          git \
          gnupg \
          libffi-dev \
          lsb-release \
          ruby-dev \
          wget \
        --no-install-recommends > /dev/null \
      && apt-get install -qq {% if codename != "buster" and codename != "focal" %} -t {{ codename }}-backports {% endif %} debhelper \
      && rm -r /var/lib/apt/lists/*

RUN gem install --no-document fpm
RUN adduser --shell /bin/bash --disabled-password --gecos "" builder
COPY ./files/MyConfig.pm /home/builder/.cpan/CPAN/
RUN chown -R builder:builder /home/builder/
