FROM {{ distro }}:{{ codename }}

ARG UID=1000
ARG GID=1000

ENV DEBIAN_FRONTEND noninteractive
COPY sources.list.{{ codename }} /etc/apt/sources.list

RUN apt-get update -qq \
      && apt-get install -qq \
          apt-transport-https \
          build-essential \
          curl \
          devscripts \
          fakeroot \
          git \
          gnupg \
          libffi-dev \
          libperl-dev \
          lsb-release \
          ruby-dev \
          wget \
        --no-install-recommends > /dev/null \
      && apt-get install -qq {% if codename == "bionic" %} -t {{ codename }}-backports {% endif %} debhelper \
      && rm -r /var/lib/apt/lists/*

RUN gem install --no-document fpm
RUN groupadd -g $GID builder || true && \
    adduser --shell /bin/bash --disabled-password --gecos "" --uid $UID --gid $GID builder
COPY ./files/MyConfig.pm /home/builder/.cpan/CPAN/
RUN chown -R builder:builder /home/builder/
